"""
Расписание гонок Формулы 1 на сезон 2026 года.

Источник данных: официальный сайт formula1.com
Все времена хранятся в UTC и конвертируются в часовой пояс пользователя при выводе.
"""

from datetime import datetime

SCHEDULE_2026: list[dict] = [
    {
        "round": 1,
        "name": "Гран-при Австралии",
        "circuit": "Альберт Парк",
        "country": "Австралия",
        "flag": "🇦🇺",
        "sessions": {
            "fp1":               datetime(2026, 3, 6, 1, 30),
            "fp2":               datetime(2026, 3, 6, 5, 0),
            "fp3":               datetime(2026, 3, 7, 1, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 3, 7, 5, 0),
            "race":              datetime(2026, 3, 8, 4, 0),
        },
    },
    {
        "round": 2,
        "name": "Гран-при Китая",
        "circuit": "Шанхайский международный автодром",
        "country": "Китай",
        "flag": "🇨🇳",
        "sessions": {
            "fp1":               datetime(2026, 3, 13, 3, 30),
            "fp2":               None,
            "fp3":               None,
            "sprint_qualifying": datetime(2026, 3, 13, 7, 30),
            "sprint":            datetime(2026, 3, 14, 3, 0),
            "qualifying":        datetime(2026, 3, 14, 7, 0),
            "race":              datetime(2026, 3, 15, 7, 0),
        },
    },
    {
        "round": 3,
        "name": "Гран-при Японии",
        "circuit": "Сузука",
        "country": "Япония",
        "flag": "🇯🇵",
        "sessions": {
            "fp1":               datetime(2026, 3, 27, 2, 30),
            "fp2":               datetime(2026, 3, 27, 6, 0),
            "fp3":               datetime(2026, 3, 28, 2, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 3, 28, 6, 0),
            "race":              datetime(2026, 3, 29, 5, 0),
        },
    },
    {
        "round": 4,
        "name": "Гран-при Майами",
        "circuit": "Майами Интернэшнл Отодром",
        "country": "США",
        "flag": "🇺🇸",
        "sessions": {
            "fp1":               datetime(2026, 5, 1, 16, 30),
            "fp2":               None,
            "fp3":               None,
            "sprint_qualifying": datetime(2026, 5, 1, 20, 30),
            "sprint":            datetime(2026, 5, 2, 16, 0),
            "qualifying":        datetime(2026, 5, 2, 20, 0),
            "race":              datetime(2026, 5, 3, 20, 0),
        },
    },
    {
        "round": 5,
        "name": "Гран-при Канады",
        "circuit": "Жиль Вильнёв",
        "country": "Канада",
        "flag": "🇨🇦",
        "sessions": {
            "fp1":               datetime(2026, 5, 22, 17, 30),
            "fp2":               datetime(2026, 5, 22, 21, 0),
            "fp3":               datetime(2026, 5, 23, 16, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 5, 23, 20, 0),
            "race":              datetime(2026, 5, 24, 18, 0),
        },
    },
    {
        "round": 6,
        "name": "Гран-при Монако",
        "circuit": "Трасса Монако",
        "country": "Монако",
        "flag": "🇲🇨",
        "sessions": {
            "fp1":               datetime(2026, 6, 5, 11, 30),
            "fp2":               datetime(2026, 6, 5, 15, 0),
            "fp3":               datetime(2026, 6, 6, 10, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 6, 6, 14, 0),
            "race":              datetime(2026, 6, 7, 13, 0),
        },
    },
    {
        "round": 7,
        "name": "Гран-при Барселоны-Каталунья",
        "circuit": "Каталунья",
        "country": "Испания",
        "flag": "🇪🇸",
        "sessions": {
            "fp1":               datetime(2026, 6, 12, 11, 30),
            "fp2":               datetime(2026, 6, 12, 15, 0),
            "fp3":               datetime(2026, 6, 13, 10, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 6, 13, 14, 0),
            "race":              datetime(2026, 6, 14, 13, 0),
        },
    },
    {
        "round": 8,
        "name": "Гран-при Австрии",
        "circuit": "Ред Булл Ринг",
        "country": "Австрия",
        "flag": "🇦🇹",
        "sessions": {
            "fp1":               datetime(2026, 6, 26, 11, 30),
            "fp2":               datetime(2026, 6, 26, 15, 0),
            "fp3":               datetime(2026, 6, 27, 10, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 6, 27, 14, 0),
            "race":              datetime(2026, 6, 28, 13, 0),
        },
    },
    {
        "round": 9,
        "name": "Гран-при Великобритании",
        "circuit": "Сильверстоун",
        "country": "Великобритания",
        "flag": "🇬🇧",
        "sessions": {
            "fp1":               datetime(2026, 7, 3, 12, 30),
            "fp2":               datetime(2026, 7, 3, 16, 0),
            "fp3":               datetime(2026, 7, 4, 11, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 7, 4, 15, 0),
            "race":              datetime(2026, 7, 5, 14, 0),
        },
    },
    {
        "round": 10,
        "name": "Гран-при Бельгии",
        "circuit": "Спа-Франкоршам",
        "country": "Бельгия",
        "flag": "🇧🇪",
        "sessions": {
            "fp1":               datetime(2026, 7, 17, 11, 30),
            "fp2":               datetime(2026, 7, 17, 15, 0),
            "fp3":               datetime(2026, 7, 18, 10, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 7, 18, 14, 0),
            "race":              datetime(2026, 7, 19, 13, 0),
        },
    },
    {
        "round": 11,
        "name": "Гран-при Венгрии",
        "circuit": "Хунгароринг",
        "country": "Венгрия",
        "flag": "🇭🇺",
        "sessions": {
            "fp1":               datetime(2026, 7, 24, 11, 30),
            "fp2":               datetime(2026, 7, 24, 15, 0),
            "fp3":               datetime(2026, 7, 25, 10, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 7, 25, 14, 0),
            "race":              datetime(2026, 7, 26, 13, 0),
        },
    },
    {
        "round": 12,
        "name": "Гран-при Нидерландов",
        "circuit": "Зандворт",
        "country": "Нидерланды",
        "flag": "🇳🇱",
        "sessions": {
            "fp1":               datetime(2026, 8, 21, 10, 30),
            "fp2":               datetime(2026, 8, 21, 14, 0),
            "fp3":               datetime(2026, 8, 22, 9, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 8, 22, 13, 0),
            "race":              datetime(2026, 8, 23, 13, 0),
        },
    },
    {
        "round": 13,
        "name": "Гран-при Италии",
        "circuit": "Монца",
        "country": "Италия",
        "flag": "🇮🇹",
        "sessions": {
            "fp1":               datetime(2026, 9, 4, 11, 30),
            "fp2":               datetime(2026, 9, 4, 15, 0),
            "fp3":               datetime(2026, 9, 5, 10, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 9, 5, 14, 0),
            "race":              datetime(2026, 9, 6, 13, 0),
        },
    },
    {
        "round": 14,
        "name": "Гран-при Испании (Мадрид)",
        "circuit": "Мадрид Мотор Сити",
        "country": "Испания",
        "flag": "🇪🇸",
        "sessions": {
            "fp1":               datetime(2026, 9, 11, 11, 30),
            "fp2":               datetime(2026, 9, 11, 15, 0),
            "fp3":               datetime(2026, 9, 12, 10, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 9, 12, 14, 0),
            "race":              datetime(2026, 9, 13, 13, 0),
        },
    },
    {
        "round": 15,
        "name": "Гран-при Азербайджана",
        "circuit": "Городская трасса Баку",
        "country": "Азербайджан",
        "flag": "🇦🇿",
        "sessions": {
            "fp1":               datetime(2026, 9, 24, 9, 30),
            "fp2":               datetime(2026, 9, 24, 13, 0),
            "fp3":               datetime(2026, 9, 25, 8, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 9, 25, 12, 0),
            "race":              datetime(2026, 9, 26, 11, 0),
        },
    },
    {
        "round": 16,
        "name": "Гран-при Сингапура",
        "circuit": "Марина Бэй",
        "country": "Сингапур",
        "flag": "🇸🇬",
        "sessions": {
            "fp1":               datetime(2026, 10, 9, 9, 30),
            "fp2":               datetime(2026, 10, 9, 13, 0),
            "fp3":               datetime(2026, 10, 10, 9, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 10, 10, 13, 0),
            "race":              datetime(2026, 10, 11, 12, 0),
        },
    },
    {
        "round": 17,
        "name": "Гран-при США",
        "circuit": "Сёркит оф зе Америкас, Остин",
        "country": "США",
        "flag": "🇺🇸",
        "sessions": {
            "fp1":               datetime(2026, 10, 23, 17, 30),
            "fp2":               None,
            "fp3":               None,
            "sprint_qualifying": datetime(2026, 10, 23, 21, 30),
            "sprint":            datetime(2026, 10, 24, 17, 0),
            "qualifying":        datetime(2026, 10, 24, 21, 0),
            "race":              datetime(2026, 10, 25, 19, 0),
        },
    },
    {
        "round": 18,
        "name": "Гран-при Мексики",
        "circuit": "Аутодромо Эрманос Родригес",
        "country": "Мексика",
        "flag": "🇲🇽",
        "sessions": {
            "fp1":               datetime(2026, 10, 30, 19, 30),
            "fp2":               datetime(2026, 10, 30, 23, 0),
            "fp3":               datetime(2026, 10, 31, 18, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 10, 31, 22, 0),
            "race":              datetime(2026, 11, 1, 20, 0),
        },
    },
    {
        "round": 19,
        "name": "Гран-при Бразилии",
        "circuit": "Интерлагос",
        "country": "Бразилия",
        "flag": "🇧🇷",
        "sessions": {
            "fp1":               datetime(2026, 11, 6, 14, 30),
            "fp2":               None,
            "fp3":               None,
            "sprint_qualifying": datetime(2026, 11, 6, 18, 30),
            "sprint":            datetime(2026, 11, 7, 14, 0),
            "qualifying":        datetime(2026, 11, 7, 18, 0),
            "race":              datetime(2026, 11, 8, 17, 0),
        },
    },
    {
        "round": 20,
        "name": "Гран-при Лас-Вегаса",
        "circuit": "Лас-Вегас Стрип Сёркит",
        "country": "США",
        "flag": "🇺🇸",
        "sessions": {
            "fp1":               datetime(2026, 11, 20, 4, 30),
            "fp2":               datetime(2026, 11, 20, 8, 0),
            "fp3":               datetime(2026, 11, 21, 4, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 11, 21, 6, 0),
            "race":              datetime(2026, 11, 22, 6, 0),
        },
    },
    {
        "round": 21,
        "name": "Гран-при Катара",
        "circuit": "Лусаил Интернэшнл Сёркит",
        "country": "Катар",
        "flag": "🇶🇦",
        "sessions": {
            "fp1":               datetime(2026, 11, 27, 12, 30),
            "fp2":               None,
            "fp3":               None,
            "sprint_qualifying": datetime(2026, 11, 27, 16, 30),
            "sprint":            datetime(2026, 11, 28, 12, 0),
            "qualifying":        datetime(2026, 11, 28, 16, 0),
            "race":              datetime(2026, 11, 29, 15, 0),
        },
    },
    {
        "round": 22,
        "name": "Гран-при Абу-Даби",
        "circuit": "Яс Марина",
        "country": "ОАЭ",
        "flag": "🇦🇪",
        "sessions": {
            "fp1":               datetime(2026, 12, 4, 9, 30),
            "fp2":               datetime(2026, 12, 4, 13, 0),
            "fp3":               datetime(2026, 12, 5, 9, 30),
            "sprint_qualifying": None,
            "sprint":            None,
            "qualifying":        datetime(2026, 12, 5, 13, 0),
            "race":              datetime(2026, 12, 6, 13, 0),
        },
    },
]

# Человекочитаемые названия сессий
SESSION_NAMES: dict[str, str] = {
    "fp1":               "🔧 Свободная практика 1",
    "fp2":               "🔧 Свободная практика 2",
    "fp3":               "🔧 Свободная практика 3",
    "sprint_qualifying": "⚡ Спринт-квалификация",
    "sprint":            "⚡ Спринт",
    "qualifying":        "🏁 Квалификация",
    "race":              "🏆 Гонка",
}